tarjetacredito.cliente/Models/Cliente.cs
namespace tarjetacredito.cliente.Models
{
    public class Cliente
    {
        public int Id { get; set; }

        public string Nombres { get; set; } = null!;

        public string Apellidos { get; set; } = null!;

        public static implicit operator Cliente(int v)
        {
            throw new NotImplementedException();
        }
    }
}

tarjetacredito.cliente/Models/ErrorViewModel.cs
namespace tarjetacredito.cliente.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

tarjetacredito.cliente/Models/Movimientos.cs
namespace tarjetacredito.cliente.Models
{
    public class Movimientos
    {
        public int Id { get; set; }

        public int IdTarjeta { get; set; }

        public DateTime FTransaccion { get; set; }

        public string Descripcion { get; set; } = null!;

        public decimal Monto { get; set; }
    }
}

tarjetacredito.cliente/Models/Tarjeta.cs
namespace tarjetacredito.cliente.Models
{
    public class Tarjeta
    {
        public int Id { get; set; }

        public int IdCliente { get; set; }

        public string Nombre { get; set; } = null!;

        public string NTarjeta { get; set; } = null!;

        public string FVencimiento { get; set; } = null!;

        public bool Activa { get; set; }

        public decimal Limite { get; set; }

        public decimal Disponible { get; set; }

        public decimal PContado { get; set; }

        public decimal PMinimo { get; set; }
    }
}

tarjetacredito.cliente/Controllers/BancoAController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using tarjetacredito.cliente.Models;
using tarjetacredito.cliente.Servicios;


namespace tarjetacredito.cliente.Controllers
{
    public class BancoAController : Controller
    {
        private readonly Itarjeta _servicioApi;

        public BancoAController(Itarjeta servicioApi)
        {
            _servicioApi = servicioApi;
        }

        public async Task<IActionResult> Index()
        {
            //para este ejemplo se enviara el id del cliente manual y proceder con el resto automatico.
            Cliente cliente = await _servicioApi.Client(1);
            var nombre = cliente.Nombres + " " + cliente.Apellidos;
            ViewBag.Accion = nombre;
            List<Tarjeta> tarjeta = await _servicioApi.ListaTarjetas(1);
            return View(tarjeta);
        }

        public async Task<IActionResult> Pagar(int id)
        {
            Movimientos pago = new();
            pago.IdTarjeta = id;
            return View(pago);
        }

        public async Task<IActionResult> Comprar(int id)
        {
            Movimientos compra = new();
            compra.IdTarjeta = id;
            return View(compra);
        }

        public async Task<IActionResult> EstadoCuenta(int id)
        {
            return View();
        }

        public async Task<IActionResult> Movimientos(int id)
        {
            List<Movimientos> tarjeta = await _servicioApi.MovimientosTar(id);

            return View(tarjeta);
        }



        [HttpPost]
        public async Task<IActionResult> PagarTc(Movimientos movimineto)
        {
            bool respuesta;

            respuesta = await _servicioApi.pagar(movimineto);

            if (respuesta)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return NoContent();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ComprarTc(Movimientos movimineto)
        {
            bool respuesta;

            respuesta = await _servicioApi.comprar(movimineto);

            if (respuesta)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return NoContent();
            }
        }

        
    }
}

tarjetacredito.cliente/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tarjetacredito.cliente.Models;

namespace tarjetacredito.cliente.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tarjetacredito.cliente/Views/BancoA/Comprar.cshtml
@model Movimientos

@{
    ViewData["Title"] = "Comprar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Comprar con tarjeta @ViewBag.Accion</h3>





<div class="card col-4">
    <div class="card-body">
        <form asp-action="comprarTC" asp-controller="BancoA" method="post">

            <div class="form-group">
                <input type="hidden" asp-for="IdTarjeta" />
                <div class="form-group">
                    <label asp-for="FTransaccion">Fecha</label>
                    <input asp-for="FTransaccion" type="date" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion">Descripcion</label>
                    <input asp-for="Descripcion" type="text" required class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Monto">Monto</label>
                    <input asp-for="Monto" type="number" min="1" max="3000" class="form-control" />
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Comprar</button>

        </form>
    </div>
</div>

<script>
    const fechaActual = new Date().toISOString().split('T')[0];
    document.getElementById('FTransaccion').min = fechaActual;

</script>


tarjetacredito.cliente/Views/BancoA/EstadoCuenta.cshtml

@{
    ViewData["Title"] = "EstadoCuenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Estado de Cuenta</h3>


tarjetacredito.cliente/Views/BancoA/Index.cshtml
@model List<Tarjeta>
@{
    ViewData["Title"] = "Inicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Bienvenido,</h3>
@ViewBag.Accion
<br />
<div class="card">
    <div class="card-header">
        Lista de Tarjetas
    </div>
    <div class="card-body">
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>N. Tarjeta</th>
                    <th>Limite</th>
                    <th>Disponible</th>
                    <th>Pago Contado</th>
                    <th>Pago Minimo</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>XXXXXXXXXXXX @item.NTarjeta.Substring(item.NTarjeta.Length -4)</td>
                        <td>$@item.Limite</td>
                        <td>$@item.Disponible</td>
                        <td>$@item.PContado</td>
                        <td>$@item.PMinimo</td>
                        <td>
                            <a asp-action="Pagar" asp-controller="BancoA" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Pagar</a>
                            <a asp-action="Comprar" asp-controller="BancoA" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Comprar</a>
                            <a asp-action="Movimientos" asp-controller="BancoA" asp-route-id="@item.Id" class="btn btn-success btn-sm">Movimientos</a>
                            <a asp-action="EstadoCuenta" asp-controller="BancoA" asp-route-id="@item.Id" class="btn btn-info btn-sm">Estado de cuenta</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

tarjetacredito.cliente/Views/BancoA/Movimientos.cshtml
@model List<Movimientos>
@{
    ViewData["Title"] = "Movimientos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Movimientos</h3>

<div class="card">
    <div class="card-header">
        Lista de movimientos
    </div>
    <div class="card-body">
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Descripcion</th>
                    <th>Monto</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.FTransaccion.ToString("dd/MM/yyyy")</td>
                            <td>@item.Descripcion</td>
                            <td>$@item.Monto</td>
                        </tr>
                    }
                }
                else
                {
                    <td>Sin Movimientos</td>
                }
            </tbody>
        </table>
    </div>
</div>

tarjetacredito.cliente/Views/BancoA/Pagar.cshtml
@model Movimientos

@{
    ViewData["Title"] = "Pagar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Pagar tarjeta @ViewBag.Accion</h3>


<div class="card col-4">
    <div class="card-body">
        <form asp-action="PagarTc" asp-controller="BancoA" method="post">

            <div class="form-group">
                <input type="hidden" asp-for="IdTarjeta" />
                <div class="form-group">
                    <label asp-for="FTransaccion">Fecha</label>
                    <input asp-for="FTransaccion" type="date" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion">Descripcion</label>
                    <input asp-for="Descripcion" type="text" required class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Monto">Monto</label>
                    <input asp-for="Monto" type="number" min="1" max="3000" class="form-control" />
                </div>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Pagar</button>

        </form>
    </div>
</div>

<script>
    const fechaActual = new Date().toISOString().split('T')[0];
    document.getElementById('FTransaccion').min = fechaActual;

</script>

tarjetacredito.cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

tarjetacredito.cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tarjetacredito.cliente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="BancoA" asp-action="Index">Mis Tarjetas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tarjetacredito.cliente - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>